# 서버
server:
  port: 8080
  servlet:
    context-path: /myfarm
    encoding:
      force-response: true # 한글 깨짐

# 스프링
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: /WEB-INF/resources/
  datasource:
    url: jdbc:h2:./myfarm
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
#    url: jdbc:postgresql://localhost:5433/farmstory

  jpa:
    hibernate:
      ddl-auto: create   # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
#        show-sql: true       # sql 쿼리를 보여줍니다.
        format_sql: true
    open-in-view: false

# 로그
logging:
  level:
    org.hibernate.sql: debug

# swagger
springdoc:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json