
# 서버
server:
  port: 8080
  servlet:
    context-path: /myfarm

# 스프링
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: /WEB-INF/resources/
  datasource:
    url: jdbc:postgresql://localhost:5433/farmstory
    username: jmBaek
    password: sjheeq1245!@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # option type: create, create-drop, update, validate, none
    show-sql: true       # sql 쿼리를 보여줍니다.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
    open-in-view: false

# 로그
logging:
  level:
    org.hibernate.sql: debug
    com.farmstory: debug

# swagger
springdoc:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json